### ISSUE TITLE
Small typo on your Gates page

### ISSUE THREAD

**Issue by fedmich** [vlandham/gates_bubbles#1]
Hello,

on your demo page, http://vallandingham.me/gates_bubbles/#

The link to Github on the footer is wrong, and is missing a quote in there

**Comment by wweberfr** [comment]
Hi,

I downloaded the ZIP file.
My problem : When I open the index.html file, the title and links are here but the screen (where the bubbles are supposed to be, is blank,

I tried with Chrome and IE,
I missed something ?

Thx

**Comment by vlandham** [comment]
Hi @fedmich  - some how I forgot long ago to thank you for the comment. My apologies for not saying so before. Thank you!

Hi @wweberfr 

I realized after your post that I had neglected to add a readme to the repo. I have added one now.

My guess is that you need to run it from a web server on your machine to get the data to load properly. I tried to detail the steps in the readme - https://github.com/vlandham/gates_bubbles - so try that out. If it doesn't work, let me know.
